import Head from 'next/head'
 import Image from 'next/image'
 import styles from '../styles/Home.module.css'
 import Nav from 'react-bootstrap/Nav';
 import NavDropdown from 'react-bootstrap/NavDropdown';
import Carousel from 'react-bootstrap/Carousel';

 import 'bootstrap/dist/css/bootstrap.min.css'
 
 export default function Home() {
   return (
     <div className={styles.container}>
       <Head>
         <title>Create Next App</title>
         <meta name="description" content="Generated by create next app" />
         <link rel="icon" href="/favicon.ico" />
       </Head>
       <h1>WELCOME TO CAR BIKE 360</h1>

    <Carousel fade>
      <Carousel.Item>
        <Image
          className="d-block w-100"
          src="/img5.jpg" layout="responsive" width="100" height="50" 
          alt="First slide"
        />
        <Carousel.Caption>
        <div className={styles.cards}>
        <h3>Ferrari</h3>
             <p>Automatic Car</p>
             <h4>RS  1.5 crore onwards</h4>
          </div>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
      <Image
          className="d-block w-100"
          src="/for1.jpeg" layout="responsive" width="100" height="50" 
          alt="First slide"
        />

        <Carousel.Caption>
        <div className={styles.cards}>
        <h3>Fortuner</h3>
             <p>Mannul</p>
             <h4>RS 20.00 lakhs onwards</h4>
          </div>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
      <Image
          className="d-block w-100"
          src="/curv.jpg" layout="responsive" width="100" height="50" 
          alt="First slide"
        />

        <Carousel.Caption>
        <div className={styles.cards}>
        <h3>Tata curv</h3>
             <p>Automatic</p>
             <h4>RS 20.00 lakhs onwards</h4>
          </div>
        </Carousel.Caption>
      </Carousel.Item>
      <Carousel.Item>
      <Image
          className="d-block w-100"
          src="/sco1.jpg" layout="responsive" width="100" height="50" 
          alt="First slide"
        />

        <Carousel.Caption>
        <div className={styles.cards}>
        <h3>Scorpio</h3>
             <p>Automatic</p>
             <h4>RS 20.00 lakhs onwards</h4>
          </div>
        </Carousel.Caption>
      </Carousel.Item>
    </Carousel>
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          BEST CAR IN INDIA'S
        </h1>

 
       <div className={styles.grid}>
          <div className={styles.card}>
            <Image src="/img4.jpeg" width="200" height="180px" />
            <h2>Scorpio</h2>
            <p>Automatic</p>
            <h4>RS 20.00 lakhs onwards</h4>
            <div className={styles.details}>
              <a href="/scorpio">View details</a>
            </div>
            </div>
            <div className={styles.card}>
            <Image src="/img2.jpeg" width="200" height="180px" />
            <h2>Forturner</h2>
            <p>Manual</p>
            <h4>RS 25.00 lakhs onwards</h4>
            <div className={styles.details}>
              <a href="/for">View details</a>
            </div>
            </div>
            <div className={styles.card}>
            <Image src="/img1.jpeg"  width="200" height="180px" />
            <h2>Ferrari</h2>
            <p>Automatic</p>
            <h4>RS 1.5 crore onwards</h4>
            <div className={styles.details}>
              <a href="https://www.carbike360.com/">View details</a>
            </div>
            </div>
            <div className={styles.card}>
            <Image src="/img3.jpeg" width="200" height="180px" />
            <h2>Tata Curvv</h2>
            <p>Automatic</p>
            <h4>RS 20.00 lakhs onwards</h4>
            <div className={styles.details}>
              <a href="https://www.carbike360.com/">View details</a>
            </div>
            </div>
            </div>
            </main>
            </div>
 </div>
   )
 }